version: "3"
services:
  bootstrap-node:
    build:
      context: ./kademlia-node
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network
    environment:
      - NODE_PORT=3000
      - IS_BOOTSTRAP=true
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:30000:50000"
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  kademlia-node:
    build:
      context: ./kademlia-node
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network
    ports:
      - "127.0.0.1::50000"
    external_links:
      - bootstrap-node:bootstrap-node
    environment:
      - BOOSTRAP_NODE_HOSTNAME=bootstrap-node
      - BOOSTRAP_NODE_PORT=3000
      - NODE_PORT=3000
      - IS_BOOTSTRAP=false
    depends_on:
      bootstrap-node:
        condition: service_healthy
networks:
  kademlia_network: